### ISSUE TITLE
Using cookiecutter --overwrite deletes existing code

### ISSUE THREAD

**Issue by EbenezerA99** [SterlingPeet/cookiecutter-fprime-deployment#8]
So when I run  `cookiecutter --overwrite-if-exists --config-file={{cookiecutter.deployment_dir_name}}/.cookiecutterrc gh:sterlingpeet/cookiecutter-fprime-deployment` the cookiecutter automatically deletes some of the work I already had within the topology such as importing components etc.

Is there a way for us to run this command and have it _only change_ the directly affected lines vs having it also delete the lines that I added in for my deployment?

**Comment by SterlingPeet** [comment]
That problem is outside the scope of the software within this repository.  If you use the ``--overwrite-if-exists`` option with ``cookiecutter``, you have explicitly asked for existing files to be thrown away.  That is what the option means.

However, when you do that, you can use your ``git`` tool to select template updates for staging, and revert lines that you had changed manually.  Utilizing this process is expected when you invoke the ``--overwrite-if-exists`` option.

**Comment by EbenezerA99** [comment]
Got it, thanks
